[tools]
"npm:@astrojs/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:typescript-language-server" = "latest"

[settings]
experimental = true
lockfile = true

npm.package_manager = "pnpm"
